// <auto-generated />
using System;
using HerreraSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HerreraSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HerreraSystemContext))]
    partial class HerreraSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BatchStatusId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RestockId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitProductionCost")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Batches__3214EC07F0175079");

                    b.HasIndex("BatchStatusId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RestockId");

                    b.HasIndex(new[] { "BatchCode" }, "UQ__Batches__B22ADA8E7340E5C3")
                        .IsUnique()
                        .HasFilter("[BatchCode] IS NOT NULL");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.BatchLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BatchLoc__3214EC072F9B81E0");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "BatchId", "LocationId" }, "UQ_BatchLocation")
                        .IsUnique();

                    b.ToTable("BatchLocations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.BatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__BatchSta__3214EC0755474FB9");

                    b.ToTable("BatchStatuses");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.BusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PointOfSale")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Posaddress")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("POSAddress");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC07061A3DB2");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC0742C9F50F");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Flavor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlavorColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("FlavorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__Flavors__3214EC072A0E89A0");

                    b.ToTable("Flavors");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("MovementDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MovementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3214EC07F67FBA38");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SaleId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Lines__3214EC0738136C76");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.LinePresentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("PresentationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LinePres__3214EC07A37CA463");

                    b.HasIndex("PresentationId");

                    b.HasIndex(new[] { "LineId", "PresentationId" }, "UQ_Line_Presentation")
                        .IsUnique();

                    b.ToTable("LinePresentations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC075DA65C6F");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.MovementDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SourceLocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Movement__3214EC076F6ED98A");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("MovementId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("MovementDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MovementTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("Sign")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Movement__3214EC077C997F22");

                    b.ToTable("MovementTypes");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Municipa__3214EC072203A186");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TotalOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07D1B14B5E");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ_OrderCode")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPriceId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC0723A315DA");

                    b.HasIndex("BatchId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPriceId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__OrderSta__3214EC073A31751A");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredBy")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07A9E7F76F");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("RegisteredBy");

                    b.HasIndex("SaleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentM__3214EC07E82D4CDB");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentT__3214EC07D013BFE6");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PresentationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Presenta__3214EC07994D0105");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PriceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PriceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__PriceTyp__3214EC074AFD7546");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FlavorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LinePresentationId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC078717DBEB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FlavorId");

                    b.HasIndex("LinePresentationId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LinePresentationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PriceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__ProductP__3214EC0795BEEC37");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LinePresentationId");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Restock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("RestockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("RestockDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Producti__3214EC073165B437");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "RestockCode" }, "UQ_RestockCode")
                        .IsUnique();

                    b.ToTable("Restocks");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC072E1E2D97");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("SaleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SaleTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSale")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Sales__3214EC070AAA74F8");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SaleTypeId");

                    b.HasIndex(new[] { "SaleCode" }, "UQ_SaleCode")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppliedPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LineSubtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasComputedColumnSql("([Quantity]*[AppliedPrice])", false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SaleDeta__3214EC07A5B246F4");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.SaleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SaleTypeDescription")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SaleTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SaleType__3214EC0723E150E3");

                    b.ToTable("SaleTypes");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC072725DF1E");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105345433F74E")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__C9F2845638A1D3E6")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3214EC07346CF698");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "UQ_User_Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Batch", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.BatchStatus", "BatchStatus")
                        .WithMany("Batches")
                        .HasForeignKey("BatchStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Batch_Status");

                    b.HasOne("HerreraSystem.Domain.Entities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Batch_Product");

                    b.HasOne("HerreraSystem.Domain.Entities.Restock", "Restock")
                        .WithMany("Batches")
                        .HasForeignKey("RestockId")
                        .IsRequired()
                        .HasConstraintName("FK_Batch_Restock");

                    b.Navigation("BatchStatus");

                    b.Navigation("Product");

                    b.Navigation("Restock");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.BatchLocation", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Batch", "Batch")
                        .WithMany("BatchLocations")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_BatchLocation_Batch");

                    b.HasOne("HerreraSystem.Domain.Entities.Location", "Location")
                        .WithMany("BatchLocations")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_BatchLocation_Location");

                    b.Navigation("Batch");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Customer", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Municipality", "Municipality")
                        .WithMany("Customers")
                        .HasForeignKey("MunicipalityId")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_Municipality");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_InvMov_User_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.MovementType", "MovementType")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("MovementTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_InvMov_MovementType");

                    b.HasOne("HerreraSystem.Domain.Entities.Order", "Order")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_InvMov_Order");

                    b.HasOne("HerreraSystem.Domain.Entities.Sale", "Sale")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("FK_InvMov_Sale");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("MovementType");

                    b.Navigation("Order");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.LinePresentation", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Line", "Line")
                        .WithMany("LinePresentations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Line");

                    b.HasOne("HerreraSystem.Domain.Entities.Presentation", "Presentation")
                        .WithMany("LinePresentations")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Presentation");

                    b.Navigation("Line");

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.MovementDetail", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Batch", "Batch")
                        .WithMany("MovementDetails")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_MovDet_Batch");

                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("MovementDetails")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MovDet_User_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.Location", "DestinationLocation")
                        .WithMany("MovementDetailDestinationLocations")
                        .HasForeignKey("DestinationLocationId")
                        .HasConstraintName("FK_MovDet_DestLoc");

                    b.HasOne("HerreraSystem.Domain.Entities.InventoryMovement", "Movement")
                        .WithMany("MovementDetails")
                        .HasForeignKey("MovementId")
                        .IsRequired()
                        .HasConstraintName("FK_MovDet_Movement");

                    b.HasOne("HerreraSystem.Domain.Entities.Location", "SourceLocation")
                        .WithMany("MovementDetailSourceLocations")
                        .HasForeignKey("SourceLocationId")
                        .HasConstraintName("FK_MovDet_SourceLoc");

                    b.Navigation("Batch");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DestinationLocation");

                    b.Navigation("Movement");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Department", "Department")
                        .WithMany("Municipalities")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Department_Municipality");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Order_User_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Customer");

                    b.HasOne("HerreraSystem.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Status");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Batch", "Batch")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_OrdDet_Batch");

                    b.HasOne("HerreraSystem.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdDet_Order");

                    b.HasOne("HerreraSystem.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdDet_Product");

                    b.HasOne("HerreraSystem.Domain.Entities.ProductPrice", "ProductPrice")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductPriceId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdDet_Price");

                    b.Navigation("Batch");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductPrice");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Method");

                    b.HasOne("HerreraSystem.Domain.Entities.User", "RegisteredByNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("RegisteredBy")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_User_RegisteredBy");

                    b.HasOne("HerreraSystem.Domain.Entities.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Sale");

                    b.Navigation("PaymentMethod");

                    b.Navigation("RegisteredByNavigation");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Product", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Products")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_User_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.Flavor", "Flavor")
                        .WithMany("Products")
                        .HasForeignKey("FlavorId")
                        .IsRequired()
                        .HasConstraintName("FK_Flavor");

                    b.HasOne("HerreraSystem.Domain.Entities.LinePresentation", "LinePresentation")
                        .WithMany("Products")
                        .HasForeignKey("LinePresentationId")
                        .IsRequired()
                        .HasConstraintName("FK_LinePresentation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Flavor");

                    b.Navigation("LinePresentation");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.ProductPrice", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ProductPrices")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_User_Price_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.LinePresentation", "LinePresentation")
                        .WithMany("ProductPrices")
                        .HasForeignKey("LinePresentationId")
                        .HasConstraintName("FK_LinePresentation_Price");

                    b.HasOne("HerreraSystem.Domain.Entities.PriceType", "PriceType")
                        .WithMany("ProductPrices")
                        .HasForeignKey("PriceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PriceType");

                    b.HasOne("HerreraSystem.Domain.Entities.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Product_Price");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("LinePresentation");

                    b.Navigation("PriceType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Restock", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Restocks")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Restock_User_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Sale", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_User_CreatedBy");

                    b.HasOne("HerreraSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_Customer");

                    b.HasOne("HerreraSystem.Domain.Entities.Order", "Order")
                        .WithMany("Sales")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Sale_Order");

                    b.HasOne("HerreraSystem.Domain.Entities.PaymentType", "PaymentType")
                        .WithMany("Sales")
                        .HasForeignKey("PaymentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_PaymentType");

                    b.HasOne("HerreraSystem.Domain.Entities.SaleType", "SaleType")
                        .WithMany("Sales")
                        .HasForeignKey("SaleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_SaleType");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");

                    b.Navigation("SaleType");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.SaleDetail", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Batch", "Batch")
                        .WithMany("SaleDetails")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleDet_Batch");

                    b.HasOne("HerreraSystem.Domain.Entities.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleDet_Product");

                    b.HasOne("HerreraSystem.Domain.Entities.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleDet_Sale");

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HerreraSystem.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Role");

                    b.HasOne("HerreraSystem.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Batch", b =>
                {
                    b.Navigation("BatchLocations");

                    b.Navigation("MovementDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.BatchStatus", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Department", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Flavor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.InventoryMovement", b =>
                {
                    b.Navigation("MovementDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Line", b =>
                {
                    b.Navigation("LinePresentations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.LinePresentation", b =>
                {
                    b.Navigation("ProductPrices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Location", b =>
                {
                    b.Navigation("BatchLocations");

                    b.Navigation("MovementDetailDestinationLocations");

                    b.Navigation("MovementDetailSourceLocations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.MovementType", b =>
                {
                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Municipality", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Order", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("OrderDetails");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PaymentType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Presentation", b =>
                {
                    b.Navigation("LinePresentations");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.PriceType", b =>
                {
                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductPrices");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.ProductPrice", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Restock", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.Sale", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Payments");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.SaleType", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("HerreraSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("MovementDetails");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("ProductPrices");

                    b.Navigation("Products");

                    b.Navigation("Restocks");

                    b.Navigation("Sales");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
